graph_table: graph_table.tsv # VG or GFA format
reads_table: reads_table.tsv # FASTA, FASTA.GZ, FASTQ, FASTQ.GZ
output_directory: "results"
graphchainer_threads: 4
parameters_product:
  # Sampling step factor (default 1).
  # Use >1 (<1, >0) for faster (slower), but less (more) accurate alignments.
  # It increases (decreases) the sampling sparsity of fragments.
  sampling_step: [1, 0.5, 2]
  # The length of the fragments in which the long read is split to create anchors (default 35).
  colinear_split_len: [35, 20, 70]
  # When converting an optimal chain of anchors into an alignment path,
  # split the path if the distance in the graph between consecutive anchors is greater than this value (default 10000).
  colinear_gap: [10000, 5000, 20000]
parameters_tuples:
  # sampling_step, colinear_split_len, colinear_gap
  - [1, 35, 10000]
  - [2, 35, 10000]
  - [0.5, 35, 10000]
  - [0.2, 35, 10000]