

configfile: "config.yaml"

graph_path = config["graph"]
sr_fastq_prefix = config["sr_fastq_prefix"]
lr_fasta = config["lr_fastq"]

threads = config["threads"]

rule all:
    input:
        sr = expand(f"{sr_fastq_prefix}/reads_R{{num}}.fastq", num=[1,2]),
        lr = "ONT_out.gaf"


rule short_reads:
    input:
        graph=graph_path,
        sr_fasta=lambda wildcards: f"{sr_fastq_prefix}/reads_R{{wildcards.num}}.fastq"
    output:
        f"illumina_{{num}}_out.gaf"
    threads: threads
    shell:
        "minigraph -cx sr -t {threads} {input.graph} {input.sr_fasta} > {output}"

rule long_reads:
    input:
        graph=graph_path,
        lr_fasta=lr_fasta
    output:
        "ONT_out.gaf"
    threads: threads
    shell:
        "minigraph -cx lr -t {threads} {input.graph} {input.lr_fasta} > {output}"
